# Generated by Django 5.1.2 on 2024-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("Finance", "Finance"),
                            ("Engineering", "Engineering"),
                            ("Marketing", "Marketing"),
                            ("Sales", "Sales"),
                        ],
                        default="Engineering",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Engineer", "Engineer"),
                            ("Intern", "Intern"),
                            ("Director", "Director"),
                            ("Assistant", "Assistant"),
                        ],
                        default="Engineer",
                        max_length=20,
                    ),
                ),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
    ]
